
---
# This playbook contains common plays that will be run on all nodes.

- name: set timezone to Europe/Istanbul
  timezone:
    name: "{{ timezone }}"

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: replace /etc/hosts file
  replace:
    path: /etc/hosts
    regexp: '127.0.1.1(.*)'
    replace: ''
    backup: yes

