---
# This playbook will install openldap

- name: Check if OpenLDAP is already installed.
  stat: path=/etc/init.d/slapd
  register: ldap_installed


#- name: Do not autoconfigure OpenLDAP
#  debconf: >
#    name=slapd
#    question='slapd/no_configuration'
#    value=true
#    vtype=boolean
#  tags: openldap

- name: Update apt cache if OpenLDAP is not yet installed.
  apt: update_cache=yes
  when: ldap_installed.stat.exists == false


- name: Debconf
  debconf:
    name: 'slapd'
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ openldap_debconfs }}"



- name: Install OpenLDAP package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ openldap_packages }}"
  environment: "{{ env }}"
  when: ldap_installed.stat.exists == false
  tags: openldap

- name: Install python modules
  pip:
    name: "{{ item }}"
  with_items:
    - python-ldap
    - ssh-ldap-pubkey

- name: Generate the root password for ldap
  shell: "slappasswd -h {SSHA} -s {{ openldap_slapd_admin_rootpw }}"
  register: root_password

- name: Copy config with olcRootPW
  template:
    src: "new_passwd.ldif"
    dest: "/etc/ldap/slapd.d/cn=config/olcDatabase={0}config.ldif"
    mode: "0600"
    owner: "openldap"
    group: "openldap"



#- name: Template ldap.conf
#  template:
#    src: "ldap.conf"
#    dest: "/etc/ldap/ldap.conf"
#    mode: "0754"
#    backup: yes

- name: Template ldif list
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0754"
    backup: yes
  with_items: "{{ openldap_ldif_list }}"


- name: Template data ldif list
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0754"
    backup: yes
  with_items: "{{ openldap_data_ldif_list }}"




- name: Template schema list
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0754"
    backup: yes
  with_items: "{{ openldap_schema_list }}"


- name: restart slapd
  service:
    name: slapd
    state: restarted


- name: Ensure schemas added before ldifs added
  shell: "ldapadd -h localhost -p 389 -x -D \"cn=admin,cn=config\" -f {{ item.dest }} -w {{ openldap_slapd_admin_rootpw }}"
#  args:
#    creates: "{{ item.creates }}"
  with_items: "{{ openldap_schema_list }}"
#  notify:
#   - restart slapd


- name: Add Ahenkler group,lider_console user
  shell: "ldapadd -h localhost -p 389 -x -D {{openldap_slapd_admin}} -f {{ item.dest }} -w {{ openldap_slapd_admin_rootpw }}"
  with_items: "{{ openldap_ldif_list }}"


- name: Add Ahenkler group,lider_console user
  shell: "ldapadd -h localhost -p 389 -x -D {{openldap_slapd_admin}} -f {{ item.dest }} -w {{ openldap_slapd_admin_rootpw }}"
  with_items: "{{ openldap_data_ldif_list }}"
