---
# This playbook will install ejabberd

- name: Add liderahenk Apt signing key
  apt_key:
    url: http://repo.liderahenk.org/liderahenk-archive-keyring.asc
    state: present

- name: Add liderahenk repository into sources list.
  apt_repository:
    repo: deb http://repo.liderahenk.org/liderahenk stable main
    state: present

- name: Update apt cache
  apt: update_cache=yes

- name: Install ejabberd package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ejabberd=16.06-0

- name: ejabberd.yml file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "ejabberd"
  with_items: "{{ ejabberd_conf }}"


- name: start ejabberd
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl start"

- pause: seconds=5



- name: chekc registered users
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl registered_users {{service_name}}"
  register: users



- name: register ejabberd admin
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl register admin {{ service_name }} {{ ejabberd_admin_pass }}"
  when: '"admin" not in users.stdout'

- name: register lider_sunucu user
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl register lider_sunucu {{ service_name }} {{ lider_sunucu_pass }}"
  when: '"lider_sunucu" not in users.stdout'


- name: chekc roster users
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl srg_list {{service_name}}"
  register: srg_users


- name: roster ayarlari
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl srg-create everyone {{ service_name }} \"everyone\" this_is_everyone everyone"
  when: '"everyone" not in srg_users.stdout'

- name: roster add user
  shell: "/opt/ejabberd-16.06/bin/ejabberdctl srg-user-add @all@ {{ service_name }} everyone {{ service_name }}"
  when: '"everyone" not in srg_users.stdout'