---
- hosts: all
  remote_user: root
  tasks:
    - name: install python 2
      gather_facts: false
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: update machine package cache
      apt:
         update_cache: yes

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common


- name: Install dbserver
  hosts: db
  remote_user: root

  roles:
    - db
