---
- hosts: all
  remote_user: root
  tasks:
    - name: install python 2
      gather_facts: false
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: update machine package cache
      apt:
         update_cache: yes

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common


- name: Install dbserver
  hosts: db
  remote_user: root

  roles:
    - db


- name: Install OpenLDAP
  hosts: ldap
  remote_user: root

  roles:
    - role: ldap
      openldap_slapd_tls_cert: "/etc/ssl/{{ inventory_hostname }}/{{ inventory_hostname }}.pem"
      openldap_slapd_tls_key: "/etc/ssl/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
      openldap_slapd_domain: "liderahenk.org"
      openldap_slapd_suffix: "dc=liderahenk,dc=org"
      openldap_slapd_admin: "cn=admin,dc=liderahenk,dc=org"
      openldap_slapd_admin_rootpw: admin12345


- name: Install XMPP Server
  hosts: im
  remote_user: root

  roles:
    - xmpp


- name: Install File Server
  hosts: fileserver
  remote_user: root

  roles:
    - fileserver



- name: Install Lider Server
  hosts: lider
  remote_user: root

  roles:
    - lider