---
# This playbook will install fileserver


# Add specified repository into sources list.
- apt_repository:
    repo: deb http://http.debian.net/debian jessie-backports main
    state: present

- name: Add liderahenk Apt signing key
  apt_key:
    url: http://repo.liderahenk.org/liderahenk-archive-keyring.asc
    state: present

- name: Add liderahenk repository into sources list.
  apt_repository:
    repo: deb http://repo.liderahenk.org/liderahenk stable main
    state: present

- name: Update apt cache
  apt: update_cache=yes


- name: Install openjdk-8 from jessie-backports
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    default_release: jessie-backports
    cache_valid_time: 3600
  with_items:
    - openjdk-8-jre


- name: Install lider-server package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - lider-server